export const siteConfig = {
  name: "StraWeb",
  description: "개발, 리뷰, 투자 등 관심 있는 것들을 편하게 기록하는 블로그입니다.",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000",
  locale: "ko_KR",
  author: "Narzas",
  keywords: [
    "개발 블로그",
    "프로그래밍",
    "Spring Boot",
    "React",
    "Next.js",
    "레트로 게임",
    "게임 리뷰",
    "투자",
    "일상",
    "IT",
    "백엔드",
    "앤버닉",
    "레트로 게임기",
  ],
} as const;
